name: track
description: "Easily track streaks, counters, history, and records. Effortless persistent trackers with no manual timers or storage, just define and go."
version: 1.1.2
homepage: https://github.com/jozzzzep/track
repository: https://github.com/jozzzzep/track
issue_tracker: https://github.com/jozzzzep/track/issues
topics:
  - streaks
  - counters
  - history
  - persistence
  - records

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  prf: ^2.4.2
  synchronized: ">=3.2.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences_platform_interface: ^2.4.1
  shared_preferences: ^2.5.3
