name: track
description: "Easily track streaks, counters, history, and records. Effortless persistent trackers with no manual timers or storage, just define and go."
version: 1.0.0
homepage:

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  shared_preferences_platform_interface: ^2.4.1
